<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Sprint;
use Carbon\Carbon;
use Doctrine\ORM\EntityRepository;

/**
 * SprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SprintRepository extends EntityRepository
{
    /**
     * @return Sprint
     *
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findSprintToClose()
    {
        return $this->createQueryBuilder('s')
            ->andWhere('s.expectedClosedAt < :now')
            ->setParameter('now', new \DateTime(Carbon::now()->toDateTimeString()))
            ->andWhere('s.status != \'CLOSE\'')
            ->getQuery()
            ->getSingleResult();
    }
}
